/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.HoaDonDAO;
import Entity.HoaDon;
import GUI.GUIInHoaDon;
import Entity.InHoaDon;
import java.awt.event.ActionEvent;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableRowSorter;

public class GUIHoaDon extends javax.swing.JFrame {
    HoaDonDAO hoaDonDAO = new HoaDonDAO();


    public GUIHoaDon() {
        initComponents();
        setBounds(239, 158, 1285, 685);
        loadTableData();
    }

  private void loadTableData() {
    DefaultTableModel model = (DefaultTableModel) jTableHoaDon.getModel();
    model.setRowCount(0); // Làm trống bảng
    List<HoaDon> list = hoaDonDAO.selectAll();
    Object rowData[] = new Object[9];
    for (HoaDon hd : list) {
        rowData[0] = hd.getMaHD();
        rowData[1] = hd.getTenKH();
        rowData[2] = hd.getTenNV();                         
        rowData[3] = hd.getMaMay();
        rowData[4] = hd.getTenMA();
        rowData[5] = hd.getTenDU();
        rowData[6] = hd.getLoaiThe();
        rowData[7] = hd.getTongTien();
        rowData[8] = hd.getThoiGianXuatHD();
        model.addRow(rowData);
    }
}

  public HoaDon getHoaDon() {
    HoaDon hoaDon = new HoaDon();
    hoaDon.setMaHD(txtmaHD.getText());
    hoaDon.setTenKH(txtmaMay.getText());
    hoaDon.setMaMay(txtmaKH.getText());
    hoaDon.setTenNV(txtmaNV.getText());
    hoaDon.setTongTien(Double.parseDouble(txtTongTien.getText()));
    return hoaDon;
}



    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableHoaDon = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtmaHD = new javax.swing.JTextField();
        txtmaMay = new javax.swing.JTextField();
        txtmaKH = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        btnXoaHoaDon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtda = new javax.swing.JTextField();
        txtdu = new javax.swing.JTextField();
        txtnt = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();
        btninhoadon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtmaNV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtthoigianxuat = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbldem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Tấc Cả Hóa Đơn : ");

        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });
        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimkiemKeyReleased(evt);
            }
        });

        jTableHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Khách Hàng", "Nhân Viên", "Mã Máy", "Đồ Ăn", "Đồ Uống ", "Loại Thẻ", "Tổng tiền", "Thời Gian Xuất HD"
            }
        ));
        jTableHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHoaDonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableHoaDon);

        jButton5.setBackground(new java.awt.Color(0, 0, 51));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Tìm  Hóa Đơn");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 102)));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Xem Hóa Đơn");

        jLabel15.setText("Mã Hóa Đơn");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Phải Thanh Toán :");

        jLabel18.setText("Mã Máy");

        jLabel19.setText("Khách Hàng");

        jLabel21.setText("Dịch Vụ");

        txtmaHD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 102)));
        txtmaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaHDActionPerformed(evt);
            }
        });

        txtmaMay.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtmaMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaMayActionPerformed(evt);
            }
        });

        txtmaKH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 102)));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Số tiền còn lại :");

        jTextField16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        btnXoaHoaDon.setBackground(new java.awt.Color(0, 0, 102));
        btnXoaHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaHoaDon.setText("Xóa Hóa Đơn");
        btnXoaHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHoaDonActionPerformed(evt);
            }
        });

        jLabel2.setText("Thức ăn : ");

        jLabel3.setText("Đồ Uống : ");

        jLabel4.setText("Nạp Thẻ : ");

        txtda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdaActionPerformed(evt);
            }
        });

        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });

        btninhoadon.setBackground(new java.awt.Color(255, 102, 102));
        btninhoadon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btninhoadon.setForeground(new java.awt.Color(255, 255, 255));
        btninhoadon.setText("In Hóa Đơn");
        btninhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btninhoadonMouseClicked(evt);
            }
        });
        btninhoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninhoadonActionPerformed(evt);
            }
        });

        jLabel5.setText("Nhân Viên");

        txtmaNV.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtmaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaNVActionPerformed(evt);
            }
        });

        jLabel6.setText("Thời Gian Xuất Hóa Đơn");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField16)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btninhoadon)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoaHoaDon)
                            .addComponent(jLabel22)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmaMay, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(38, 38, 38)
                                .addComponent(txtmaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(34, 34, 34)
                        .addComponent(txtmaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3))
                                        .addGap(9, 9, 9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnt)
                                    .addComponent(txtdu)
                                    .addComponent(txtda, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtthoigianxuat))
                            .addComponent(jLabel21))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtmaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtmaMay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtmaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtthoigianxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addGap(36, 36, 36)
                .addComponent(btnXoaHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btninhoadon)
                .addGap(26, 26, 26))
        );

        jLabel1.setText(".");

        lbldem.setText("jLabel7");
        lbldem.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbldemAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbldem, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1016, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel1)
                    .addComponent(lbldem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaHDActionPerformed

    private void txtmaMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaMayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaMayActionPerformed

    private void txtdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdaActionPerformed

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void jTableHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHoaDonMouseClicked
     int selectedRow = jTableHoaDon.getSelectedRow();   
    if (selectedRow != -1) {
        String maHD = jTableHoaDon.getValueAt(selectedRow, 0) != null ? jTableHoaDon.getValueAt(selectedRow, 0).toString() : "";
        String maKH = jTableHoaDon.getValueAt(selectedRow, 1) != null ? jTableHoaDon.getValueAt(selectedRow, 3).toString() : "";
        String maNV = jTableHoaDon.getValueAt(selectedRow, 2) != null ? jTableHoaDon.getValueAt(selectedRow, 2).toString() : "";
        String maMay = jTableHoaDon.getValueAt(selectedRow, 3) != null ? jTableHoaDon.getValueAt(selectedRow, 1).toString() : "";
        String da = jTableHoaDon.getValueAt(selectedRow, 4) != null ? jTableHoaDon.getValueAt(selectedRow, 4).toString() : "";
        String du = jTableHoaDon.getValueAt(selectedRow, 5) != null ? jTableHoaDon.getValueAt(selectedRow, 5).toString() : "";
        String nt = jTableHoaDon.getValueAt(selectedRow, 6) != null ? jTableHoaDon.getValueAt(selectedRow, 6).toString() : "";
        String tongTien = jTableHoaDon.getValueAt(selectedRow, 7) != null ? jTableHoaDon.getValueAt(selectedRow, 7).toString() : "";
        String thoigianxuat = jTableHoaDon.getValueAt(selectedRow, 8) != null ? jTableHoaDon.getValueAt(selectedRow, 8).toString() : "";
        
        txtmaHD.setText(maHD);    
        txtmaMay.setText(maKH);
        txtmaNV.setText(maNV);
        txtmaKH.setText(maMay);
        txtda.setText(da);
        txtdu.setText(du);
        txtnt.setText(nt);
        txtTongTien.setText(tongTien);
        txtthoigianxuat.setText(thoigianxuat);
       

        txtmaHD.setEnabled(!maHD.isEmpty());
        txtmaKH.setEnabled(!maMay.isEmpty());
        txtmaNV.setEnabled(!maNV.isEmpty());
        txtmaMay.setEnabled(!maKH.isEmpty());
        txtda.setEnabled(!da.isEmpty());
        txtdu.setEnabled(!du.isEmpty());
        txtnt.setEnabled(!nt.isEmpty());
        txtTongTien.setEnabled(!tongTien.isEmpty());
        txtthoigianxuat.setEnabled(!thoigianxuat.isEmpty());
    }
    
    }//GEN-LAST:event_jTableHoaDonMouseClicked

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2AncestorAdded

    private void txtmaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaNVActionPerformed

    private void btnXoaHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHoaDonActionPerformed
        // TODO add your handling code here:int selectedRow = jTableHoaDon.getSelectedRow();
    int selectedRow = jTableHoaDon.getSelectedRow();
    if (selectedRow != -1) {
        String maHD = jTableHoaDon.getValueAt(selectedRow, 0).toString();
        hoaDonDAO.delete(maHD);
        loadTableData();
        txtmaHD.setText("");
        txtmaNV.setText("");
        txtmaKH.setText("");
        txtmaMay.setText("");
        txtda.setText("");
        txtdu.setText("");
        txtnt.setText("");
        txtTongTien.setText("");
        txtthoigianxuat.setText("");
        JOptionPane.showMessageDialog(this, "Xóa thành công hóa đơn!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    
    }
       
    }//GEN-LAST:event_btnXoaHoaDonActionPerformed

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        
      
    }//GEN-LAST:event_txttimkiemActionPerformed

    private void txttimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyReleased
        // TODO add your handling code here:
    DefaultTableModel obj = (DefaultTableModel) jTableHoaDon.getModel();
    TableRowSorter<DefaultTableModel> obj1= new TableRowSorter<>(obj);
    jTableHoaDon.setRowSorter(obj1);
    obj1.setRowFilter(RowFilter.regexFilter(txttimkiem.getText()));
    }//GEN-LAST:event_txttimkiemKeyReleased

    private void btninhoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninhoadonActionPerformed
 
  
    }//GEN-LAST:event_btninhoadonActionPerformed

    private void lbldemAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbldemAncestorAdded
        // TODO add your handling code here:
        // Gán TableModelListener để lắng nghe sự kiện thay đổi trong bảng
    jTableHoaDon.getModel().addTableModelListener(new TableModelListener() {
        @Override
        public void tableChanged(TableModelEvent e) {
            // Kiểm tra nếu sự kiện là thêm hoặc xóa hàng
            if (e.getType() == TableModelEvent.INSERT || e.getType() == TableModelEvent.DELETE) {
                // Tính số hàng ngang hiện tại trong bảng (loại bỏ hàng tiêu đề)
                int rowCount = jTableHoaDon.getRowCount()  ; // Trừ đi hàng tiêu đề

                // Hiển thị số hàng ngang trên lbldem
                lbldem.setText("" + rowCount);
            }
        }
    });

    // Ban đầu cập nhật giá trị cho lbldem
    int initialRowCount = jTableHoaDon.getRowCount() ; // Trừ đi hàng tiêu đề
    lbldem.setText("" + initialRowCount);
    }//GEN-LAST:event_lbldemAncestorAdded

    private void btninhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninhoadonMouseClicked
    // Lấy giá trị từ các ô nhập liệu
    String maHD = txtmaHD.getText();
    String maNV = txtmaNV.getText();
    String maMay = txtmaKH.getText();
    String maKH = txtmaMay.getText();
    String da = txtda.getText();
    String du = txtdu.getText();
    String nt = txtnt.getText();
    String tongTien = txtTongTien.getText();
    String thoigianxuat = txtthoigianxuat.getText();


    // Kiểm tra nếu có ô nhập liệu nào bỏ trống
    if (maHD.isEmpty() || maNV.isEmpty() || maMay.isEmpty() || maKH.isEmpty() ||
        da.isEmpty() || du.isEmpty() || nt.isEmpty() || tongTien.isEmpty() || thoigianxuat.isEmpty()) {
        // Hiển thị thông báo nếu có ô nhập liệu bị trống
        JOptionPane.showMessageDialog(this, "Hãy chọn Hóa Đơn để thanh toán", "Lỗi", JOptionPane.ERROR_MESSAGE);
    } else {
        // Tất cả các ô nhập liệu đều được điền đầy đủ, mở class GUIInHoaDon
      GUIInHoaDon guiInHoaDon = new GUIInHoaDon(maHD, maKH, maMay, maNV, tongTien, da, du, nt);
      guiInHoaDon.updateJTable(); // Cập nhật JTable
      guiInHoaDon.setVisible(true);
    }
    }//GEN-LAST:event_btninhoadonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXoaHoaDon;
    private javax.swing.JButton btninhoadon;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableHoaDon;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JLabel lbldem;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtda;
    private javax.swing.JTextField txtdu;
    private javax.swing.JTextField txtmaHD;
    private javax.swing.JTextField txtmaKH;
    private javax.swing.JTextField txtmaMay;
    private javax.swing.JTextField txtmaNV;
    private javax.swing.JTextField txtnt;
    private javax.swing.JTextField txtthoigianxuat;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables

}
