/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.border.LineBorder;

/**
 *
 * @author Phong
 */
public class GUIOrder extends javax.swing.JFrame {

    /**
     * Creates new form Order
     */
    public GUIOrder() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Hệ Thống Quản Lý Game Home");
//        setBounds(-20, 0, 1900, 830);
        Button();
    }
void Button (){
    btnDangXuat.setBackground(Color.white);
    btn7up.setBackground(Color.white);
    btnCoffee.setBackground(Color.white);
    btnHatE.setBackground(Color.white);
    btnSprite.setBackground(Color.white);
    btnString.setBackground(Color.white);
    btnCoCa.setBackground(Color.white);;
    btnDasani.setBackground(Color.white);
    btnPepsi.setBackground(Color.white);
    btnPocari.setBackground(Color.white);
    btnSinhToDau.setBackground(Color.white);
    btnBanhMi.setBackground(Color.white);
    btnBapRang.setBackground(Color.white);
    btnBimBim.setBackground(Color.white);
    btnCungDinh.setBackground(Color.white);
    btnGaRan.setBackground(Color.white);
    btnHaoHao.setBackground(Color.white);
    btnMiTrung.setBackground(Color.white);
    btnMiY.setBackground(Color.white);
    btnNabati.setBackground(Color.white);
    btnNuiXaoBo.setBackground(Color.white);
    btnGamota.setBackground(Color.white);
    btnFUNCARD.setBackground(Color.white);
    btnGate.setBackground(Color.white);
    btnGosu.setBackground(Color.white);
    btnKulgame.setBackground(Color.white);
    btnMIGAME.setBackground(Color.white);
    btnSOHAME.setBackground(Color.white);
    btnZing.setBackground(Color.white);
    btnVCOIN.setBackground(Color.white);
    btnVGP.setBackground(Color.white);
    btn10.setBackground(Color.white);
    btn10.setBackground(Color.white);
    btn20.setBackground(Color.white);
    btn50.setBackground(Color.white);
    btn100.setBackground(Color.white);
    btn200.setBackground(Color.white);
    btn500.setBackground(Color.white);
}
private void handleButtonClick(JButton clickedButton) {
    JButton[] buttons = {btn10, btn20, btn50, btn100, btn200, btn500};

    for (JButton button : buttons) {
        if (button == clickedButton) {
            button.setBorder(new LineBorder(Color.RED, 2));
        } else {
            button.setBorder(null);
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtbChinh = new javax.swing.JTabbedPane();
        jPaneldDoAn = new javax.swing.JPanel();
        jPanelDoAnCon = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        btnBanhMi = new javax.swing.JButton();
        btnBapRang = new javax.swing.JButton();
        btnBimBim = new javax.swing.JButton();
        btnGaRan = new javax.swing.JButton();
        btnCungDinh = new javax.swing.JButton();
        btnHaoHao = new javax.swing.JButton();
        btnMiTrung = new javax.swing.JButton();
        btnMiY = new javax.swing.JButton();
        btnNabati = new javax.swing.JButton();
        btnNuiXaoBo = new javax.swing.JButton();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jPanelNuocUon = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        btn7up = new javax.swing.JButton();
        btnCoffee = new javax.swing.JButton();
        btnHatE = new javax.swing.JButton();
        btnSprite = new javax.swing.JButton();
        btnString = new javax.swing.JButton();
        btnCoCa = new javax.swing.JButton();
        btnDasani = new javax.swing.JButton();
        btnPepsi = new javax.swing.JButton();
        btnPocari = new javax.swing.JButton();
        btnSinhToDau = new javax.swing.JButton();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jPanelNapThe = new javax.swing.JPanel();
        btnVGP = new javax.swing.JButton();
        jPanelNhaCungCap = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelChonMenhGia = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn10 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn50 = new javax.swing.JButton();
        btn100 = new javax.swing.JButton();
        btn200 = new javax.swing.JButton();
        btn500 = new javax.swing.JButton();
        btnZing = new javax.swing.JButton();
        btnGosu = new javax.swing.JButton();
        btnKulgame = new javax.swing.JButton();
        btnGate = new javax.swing.JButton();
        btnVCOIN = new javax.swing.JButton();
        btnGamota = new javax.swing.JButton();
        btnSOHAME = new javax.swing.JButton();
        btnFUNCARD = new javax.swing.JButton();
        btnMIGAME = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        jPanelThoanhToan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblGhiChu = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        lblGiamGia = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblThanhToan = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JLabel();
        txtGiamGIa = new javax.swing.JLabel();
        txtThanhToan = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/iconDichVu.png"))); // NOI18N
        jLabel1.setText("Dịch vụ");

        txtSearch.setForeground(new java.awt.Color(0, 0, 51));
        txtSearch.setPreferredSize(new java.awt.Dimension(64, 15));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/search.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Khách hàng : Phan Tuấn Huy");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Tiền:");

        jtbChinh.setBackground(new java.awt.Color(0, 0, 102));
        jtbChinh.setForeground(new java.awt.Color(255, 255, 255));
        jtbChinh.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPaneldDoAn.setBackground(new java.awt.Color(255, 255, 255));
        jPaneldDoAn.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jPanelDoAnCon.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDoAnCon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Mì Hảo hảo");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("15.000 VND");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("15.000 VND");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Bánh mì");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Bắp rang");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("20.000 VND");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Bim bim");

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 0, 0));
        jLabel37.setText("10.000 VND");

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel70.setText("Gà rán");

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 0, 0));
        jLabel71.setText("25.000 VND");

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel72.setText("Mì cung đình");

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(255, 0, 0));
        jLabel73.setText("15.000 VND");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Mì trứng");

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 0, 0));
        jLabel74.setText("15.000 VND");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Mì ý");

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 0, 51));
        jLabel75.setText("30.000 VND");

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel76.setText("Nabati");

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel77.setText("nui xào bò");

        btnBanhMi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/DoAn/banhMi.jpg"))); // NOI18N
        btnBanhMi.setBorder(null);
        btnBanhMi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanhMiActionPerformed(evt);
            }
        });

        btnBapRang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/DoAn/bapRang.png"))); // NOI18N
        btnBapRang.setBorder(null);
        btnBapRang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBapRangActionPerformed(evt);
            }
        });

        btnBimBim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/DoAn/Omachi.png"))); // NOI18N
        btnBimBim.setBorder(null);
        btnBimBim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBimBimActionPerformed(evt);
            }
        });

        btnGaRan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/DoAn/comChien.png"))); // NOI18N
        btnGaRan.setBorder(null);
        btnGaRan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGaRanActionPerformed(evt);
            }
        });

        btnCungDinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/DoAn/cungDinh.jpg"))); // NOI18N
        btnCungDinh.setBorder(null);
        btnCungDinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCungDinhActionPerformed(evt);
            }
        });

        btnHaoHao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/DoAn/gaRan.jpg"))); // NOI18N
        btnHaoHao.setBorder(null);
        btnHaoHao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHaoHaoActionPerformed(evt);
            }
        });

        btnMiTrung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/DoAn/miCayKay.jpg"))); // NOI18N
        btnMiTrung.setBorder(null);
        btnMiTrung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiTrungActionPerformed(evt);
            }
        });

        btnMiY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/DoAn/miTron.png"))); // NOI18N
        btnMiY.setBorder(null);
        btnMiY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiYActionPerformed(evt);
            }
        });

        btnNabati.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/DoAn/miTrung.png"))); // NOI18N
        btnNabati.setBorder(null);
        btnNabati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNabatiActionPerformed(evt);
            }
        });

        btnNuiXaoBo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/Nuixaobo.jpg"))); // NOI18N
        btnNuiXaoBo.setBorder(null);
        btnNuiXaoBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuiXaoBoActionPerformed(evt);
            }
        });

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 0, 51));
        jLabel78.setText("10.000 VND");

        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 0, 51));
        jLabel79.setText("35.000 VND");

        javax.swing.GroupLayout jPanelDoAnConLayout = new javax.swing.GroupLayout(jPanelDoAnCon);
        jPanelDoAnCon.setLayout(jPanelDoAnConLayout);
        jPanelDoAnConLayout.setHorizontalGroup(
            jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDoAnConLayout.createSequentialGroup()
                .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBanhMi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHaoHao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBapRang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMiTrung, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(70, 70, 70)
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMiY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBimBim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNabati)
                            .addComponent(btnGaRan)))
                    .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel24))
                            .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(151, 151, 151)
                                .addComponent(jLabel23)))
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel35)
                                .addGap(183, 183, 183)
                                .addComponent(jLabel70))
                            .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel71)
                                .addGap(38, 38, 38)))))
                .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCungDinh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNuiXaoBo))
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDoAnConLayout.createSequentialGroup()
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel73))
                            .addComponent(jLabel72))
                        .addGap(84, 84, 84))))
            .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(137, 137, 137)
                .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel74))
                .addGap(134, 134, 134)
                .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                        .addComponent(jLabel75)
                        .addGap(151, 151, 151)
                        .addComponent(jLabel78))
                    .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(186, 186, 186)
                        .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel77)
                    .addComponent(jLabel79))
                .addGap(108, 108, 108))
        );
        jPanelDoAnConLayout.setVerticalGroup(
            jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDoAnConLayout.createSequentialGroup()
                .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBimBim)
                            .addComponent(btnGaRan)
                            .addComponent(btnBanhMi)
                            .addComponent(btnBapRang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDoAnConLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCungDinh)))
                .addGap(5, 5, 5)
                .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                                .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37)
                                    .addComponent(jLabel71)))
                            .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                                .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel73)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMiY)
                            .addComponent(btnNabati)
                            .addComponent(btnNuiXaoBo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel77)
                            .addComponent(jLabel76)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel75)
                            .addComponent(jLabel78)
                            .addComponent(jLabel79))
                        .addGap(44, 44, 44))
                    .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel24))
                        .addGap(60, 60, 60)
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMiTrung)
                            .addComponent(btnHaoHao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDoAnConLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20))
                            .addGroup(jPanelDoAnConLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel74)))
                        .addGap(0, 53, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPaneldDoAnLayout = new javax.swing.GroupLayout(jPaneldDoAn);
        jPaneldDoAn.setLayout(jPaneldDoAnLayout);
        jPaneldDoAnLayout.setHorizontalGroup(
            jPaneldDoAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1124, Short.MAX_VALUE)
            .addGroup(jPaneldDoAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPaneldDoAnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelDoAnCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
        jPaneldDoAnLayout.setVerticalGroup(
            jPaneldDoAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
            .addGroup(jPaneldDoAnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneldDoAnLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDoAnCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jtbChinh.addTab("Đồ ăn", jPaneldDoAn);

        jPanelNuocUon.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNuocUon.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Coca-Cola");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("15.000 VND");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("15.000 VND");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("7up");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Coffee");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("15.000 VND");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Nước hạt é");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("15.000 VND");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Sprite");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("15.000 VND");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Sting");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("15.000 VND");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Dasani");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setText("15.000 VND");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Pepsi");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 0, 51));
        jLabel34.setText("15.000 VND");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Pocari");

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Sinh tố dâu");

        btn7up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/7up.jpg"))); // NOI18N
        btn7up.setBorder(null);
        btn7up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7upActionPerformed(evt);
            }
        });

        btnCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/Coffe.png"))); // NOI18N
        btnCoffee.setBorder(null);
        btnCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoffeeActionPerformed(evt);
            }
        });

        btnHatE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/NuoHatE.png"))); // NOI18N
        btnHatE.setBorder(null);
        btnHatE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHatEActionPerformed(evt);
            }
        });

        btnSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/Sprite.png"))); // NOI18N
        btnSprite.setBorder(null);
        btnSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpriteActionPerformed(evt);
            }
        });

        btnString.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/Sting.jpg"))); // NOI18N
        btnString.setBorder(null);
        btnString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStringActionPerformed(evt);
            }
        });

        btnCoCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/coca.jpg"))); // NOI18N
        btnCoCa.setBorder(null);
        btnCoCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoCaActionPerformed(evt);
            }
        });

        btnDasani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/dasani.jpg"))); // NOI18N
        btnDasani.setBorder(null);
        btnDasani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDasaniActionPerformed(evt);
            }
        });

        btnPepsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/pepsi.jpg"))); // NOI18N
        btnPepsi.setBorder(null);
        btnPepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPepsiActionPerformed(evt);
            }
        });

        btnPocari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/pocari.jpg"))); // NOI18N
        btnPocari.setBorder(null);
        btnPocari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPocariActionPerformed(evt);
            }
        });

        btnSinhToDau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/SinhToDau.png"))); // NOI18N
        btnSinhToDau.setBorder(null);
        btnSinhToDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinhToDauActionPerformed(evt);
            }
        });

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(255, 0, 51));
        jLabel68.setText("15.000 VND");

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel69.setForeground(new java.awt.Color(255, 0, 51));
        jLabel69.setText("15.000 VND");

        javax.swing.GroupLayout jPanelNuocUonLayout = new javax.swing.GroupLayout(jPanelNuocUon);
        jPanelNuocUon.setLayout(jPanelNuocUonLayout);
        jPanelNuocUonLayout.setHorizontalGroup(
            jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNuocUonLayout.createSequentialGroup()
                .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                        .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel14)
                                .addGap(155, 155, 155)
                                .addComponent(jLabel16))
                            .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel13)
                                .addGap(126, 126, 126)
                                .addComponent(jLabel17)))
                        .addGap(144, 144, 144)
                        .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(162, 162, 162)
                                .addComponent(jLabel29))
                            .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(152, 152, 152)
                                .addComponent(jLabel30))))
                    .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn7up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCoCa, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDasani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCoffee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPepsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHatE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPocari, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSinhToDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnString, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(63, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNuocUonLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNuocUonLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(125, 125, 125))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNuocUonLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addGap(103, 103, 103))))))
            .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(162, 162, 162)
                        .addComponent(jLabel9)
                        .addGap(158, 158, 158)
                        .addComponent(jLabel10))
                    .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(jLabel33)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel34)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel68)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNuocUonLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(14, 14, 14)))
                .addGap(146, 146, 146)
                .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel69)
                    .addComponent(jLabel36))
                .addGap(92, 92, 92))
        );
        jPanelNuocUonLayout.setVerticalGroup(
            jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNuocUonLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHatE)
                    .addComponent(btnSprite)
                    .addComponent(btnString)
                    .addComponent(btn7up)
                    .addComponent(btnCoffee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                        .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel28)))
                            .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel32)))
                        .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPepsi)
                                    .addComponent(btnPocari)
                                    .addComponent(btnSinhToDau))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel10)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNuocUonLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel33)
                                .addComponent(jLabel34))
                            .addComponent(jLabel68)
                            .addComponent(jLabel69))
                        .addGap(44, 44, 44))
                    .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanelNuocUonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDasani)
                            .addGroup(jPanelNuocUonLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addGap(51, 51, 51)
                                .addComponent(btnCoCa)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jtbChinh.addTab("Nước uống", jPanelNuocUon);

        jPanelNapThe.setBackground(new java.awt.Color(255, 255, 255));

        btnVGP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/NapThe_Funcard.png"))); // NOI18N
        btnVGP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnVGP.setMaximumSize(new java.awt.Dimension(102, 34));
        btnVGP.setMinimumSize(new java.awt.Dimension(102, 34));

        jPanelNhaCungCap.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nhà cung cấp");

        javax.swing.GroupLayout jPanelNhaCungCapLayout = new javax.swing.GroupLayout(jPanelNhaCungCap);
        jPanelNhaCungCap.setLayout(jPanelNhaCungCapLayout);
        jPanelNhaCungCapLayout.setHorizontalGroup(
            jPanelNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNhaCungCapLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelNhaCungCapLayout.setVerticalGroup(
            jPanelNhaCungCapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNhaCungCapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelChonMenhGia.setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Chọn mệnh giá");

        javax.swing.GroupLayout jPanelChonMenhGiaLayout = new javax.swing.GroupLayout(jPanelChonMenhGia);
        jPanelChonMenhGia.setLayout(jPanelChonMenhGiaLayout);
        jPanelChonMenhGiaLayout.setHorizontalGroup(
            jPanelChonMenhGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelChonMenhGiaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelChonMenhGiaLayout.setVerticalGroup(
            jPanelChonMenhGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        btn10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn10.setText("10.000 VND");
        btn10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn10MouseClicked(evt);
            }
        });
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn20.setText("20.000 VND");
        btn20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btn20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn20MouseClicked(evt);
            }
        });

        btn50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn50.setText("50.000 VND");
        btn50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btn50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn50MouseClicked(evt);
            }
        });

        btn100.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn100.setText("100.000 VND");
        btn100.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btn100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn100MouseClicked(evt);
            }
        });

        btn200.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn200.setText("200.000 VND");
        btn200.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btn200.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn200MouseClicked(evt);
            }
        });

        btn500.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn500.setText("500.000 VND");
        btn500.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        btn500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn500MouseClicked(evt);
            }
        });
        btn500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500ActionPerformed(evt);
            }
        });

        btnZing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/NapThe_Zing.png"))); // NOI18N
        btnZing.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnZing.setMaximumSize(new java.awt.Dimension(102, 34));
        btnZing.setMinimumSize(new java.awt.Dimension(102, 34));

        btnGosu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/Napthe_VGP.png"))); // NOI18N
        btnGosu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnGosu.setMaximumSize(new java.awt.Dimension(102, 34));
        btnGosu.setMinimumSize(new java.awt.Dimension(102, 34));
        btnGosu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGosuActionPerformed(evt);
            }
        });

        btnKulgame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/NapThe_kulgame.png"))); // NOI18N
        btnKulgame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnKulgame.setMaximumSize(new java.awt.Dimension(102, 34));
        btnKulgame.setMinimumSize(new java.awt.Dimension(102, 34));
        btnKulgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKulgameActionPerformed(evt);
            }
        });

        btnGate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/NapThe_sohagame.png"))); // NOI18N
        btnGate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnGate.setMaximumSize(new java.awt.Dimension(102, 34));
        btnGate.setMinimumSize(new java.awt.Dimension(102, 34));

        btnVCOIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/NapThe_Gamota.png"))); // NOI18N
        btnVCOIN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnGamota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/NapThe_gosu.png"))); // NOI18N
        btnGamota.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnGamota.setMaximumSize(new java.awt.Dimension(102, 34));
        btnGamota.setMinimumSize(new java.awt.Dimension(102, 34));

        btnSOHAME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/NapThe_Gate.png"))); // NOI18N
        btnSOHAME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnSOHAME.setMaximumSize(new java.awt.Dimension(102, 34));
        btnSOHAME.setMinimumSize(new java.awt.Dimension(102, 34));

        btnFUNCARD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/NapThe_VCOIN.png"))); // NOI18N
        btnFUNCARD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        btnMIGAME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/NapThe_Migame.png"))); // NOI18N
        btnMIGAME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnMIGAME.setMaximumSize(new java.awt.Dimension(102, 34));
        btnMIGAME.setMinimumSize(new java.awt.Dimension(102, 34));

        javax.swing.GroupLayout jPanelNapTheLayout = new javax.swing.GroupLayout(jPanelNapThe);
        jPanelNapThe.setLayout(jPanelNapTheLayout);
        jPanelNapTheLayout.setHorizontalGroup(
            jPanelNapTheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNapTheLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanelNapTheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnZing, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(btnVGP, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(jPanelNapTheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVCOIN, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGamota, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanelNapTheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSOHAME, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGosu, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanelNapTheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFUNCARD, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKulgame, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanelNapTheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMIGAME, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(jPanelNapTheLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn50, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn100, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn200, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn500, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelChonMenhGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelNapTheLayout.setVerticalGroup(
            jPanelNapTheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNapTheLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanelNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanelNapTheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVGP, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVCOIN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFUNCARD, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMIGAME, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSOHAME, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanelNapTheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGate, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnZing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGamota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKulgame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnGosu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addComponent(jPanelChonMenhGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanelNapTheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelNapTheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn100, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn50, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn200, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        jtbChinh.addTab("Nạp thẻ", jPanelNapThe);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("100.000 VND");

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/logout.png"))); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addGap(463, 463, 463)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jtbChinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDangXuat)
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jtbChinh, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(89, Short.MAX_VALUE)))
        );

        jPanelThoanhToan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 0, 153));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlyduan1/Icon/cart1.png"))); // NOI18N
        jLabel2.setText("Thanh Toán");

        lblGhiChu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(0, 0, 102));
        lblGhiChu.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        lblGiamGia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblGiamGia.setForeground(new java.awt.Color(0, 0, 102));
        lblGiamGia.setText("Giảm giá:");

        lblTongTien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(0, 0, 102));
        lblTongTien.setText("Tổng tiền:");

        lblThanhToan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblThanhToan.setForeground(new java.awt.Color(0, 0, 102));
        lblThanhToan.setText("Thanh toán:");

        txtTongTien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTongTien.setForeground(new java.awt.Color(0, 0, 102));
        txtTongTien.setText("0.00 VND");
        txtTongTien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtGiamGIa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtGiamGIa.setForeground(new java.awt.Color(0, 0, 102));
        txtGiamGIa.setText("0.00 VND");
        txtGiamGIa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtThanhToan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtThanhToan.setForeground(new java.awt.Color(0, 0, 102));
        txtThanhToan.setText("0.00 VND");
        txtThanhToan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnThanhToan.setBackground(new java.awt.Color(51, 204, 0));
        btnThanhToan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.setBorder(null);

        btnHuy.setBackground(new java.awt.Color(0, 0, 51));
        btnHuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.setBorder(null);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanelThoanhToanLayout = new javax.swing.GroupLayout(jPanelThoanhToan);
        jPanelThoanhToan.setLayout(jPanelThoanhToanLayout);
        jPanelThoanhToanLayout.setHorizontalGroup(
            jPanelThoanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThoanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelThoanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                    .addGroup(jPanelThoanhToanLayout.createSequentialGroup()
                        .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelThoanhToanLayout.createSequentialGroup()
                        .addComponent(lblGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGiamGIa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelThoanhToanLayout.createSequentialGroup()
                        .addGroup(jPanelThoanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThoanhToanLayout.createSequentialGroup()
                        .addComponent(lblThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelThoanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanelThoanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelThoanhToanLayout.createSequentialGroup()
                    .addGap(66, 66, 66)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(199, Short.MAX_VALUE)))
        );
        jPanelThoanhToanLayout.setVerticalGroup(
            jPanelThoanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelThoanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelThoanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelThoanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiamGIa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelThoanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanelThoanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelThoanhToanLayout.createSequentialGroup()
                    .addContainerGap(728, Short.MAX_VALUE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanelThoanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelThoanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnSinhToDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinhToDauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSinhToDauActionPerformed

    private void btnPocariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPocariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPocariActionPerformed

    private void btnPepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPepsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPepsiActionPerformed

    private void btnDasaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDasaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDasaniActionPerformed

    private void btnCoCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoCaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCoCaActionPerformed

    private void btnStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStringActionPerformed

    private void btnSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpriteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSpriteActionPerformed

    private void btnHatEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHatEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHatEActionPerformed

    private void btnCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCoffeeActionPerformed

    private void btn7upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7upActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn7upActionPerformed

    private void btnNuiXaoBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuiXaoBoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuiXaoBoActionPerformed

    private void btnNabatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNabatiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNabatiActionPerformed

    private void btnMiYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMiYActionPerformed

    private void btnMiTrungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiTrungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMiTrungActionPerformed

    private void btnHaoHaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHaoHaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHaoHaoActionPerformed

    private void btnCungDinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCungDinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCungDinhActionPerformed

    private void btnGaRanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGaRanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGaRanActionPerformed

    private void btnBimBimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBimBimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBimBimActionPerformed

    private void btnBapRangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBapRangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBapRangActionPerformed

    private void btnBanhMiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanhMiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBanhMiActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnKulgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKulgameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKulgameActionPerformed

    private void btn500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn500ActionPerformed

    private void btn500MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn500MouseClicked
        // TODO add your handling code here:
        handleButtonClick(btn500);
    }//GEN-LAST:event_btn500MouseClicked

    private void btn200MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn200MouseClicked
        // TODO add your handling code here:
        handleButtonClick(btn200);
    }//GEN-LAST:event_btn200MouseClicked

    private void btn100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn100MouseClicked
        // TODO add your handling code here:
        handleButtonClick(btn100);
    }//GEN-LAST:event_btn100MouseClicked

    private void btn50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn50MouseClicked
        // TODO add your handling code here:
        handleButtonClick(btn50);
    }//GEN-LAST:event_btn50MouseClicked

    private void btn20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn20MouseClicked
        // TODO add your handling code here:
        handleButtonClick(btn20);
    }//GEN-LAST:event_btn20MouseClicked

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn10ActionPerformed

    private void btn10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn10MouseClicked
        // TODO add your handling code here:
        handleButtonClick(btn10);
    }//GEN-LAST:event_btn10MouseClicked

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        this.dispose();
        GUIKhachHang khachhang = new GUIKhachHang();
        khachhang.setVisible(true);
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnGosuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGosuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGosuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn100;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn200;
    private javax.swing.JButton btn50;
    private javax.swing.JButton btn500;
    private javax.swing.JButton btn7up;
    private javax.swing.JButton btnBanhMi;
    private javax.swing.JButton btnBapRang;
    private javax.swing.JButton btnBimBim;
    private javax.swing.JButton btnCoCa;
    private javax.swing.JButton btnCoffee;
    private javax.swing.JButton btnCungDinh;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDasani;
    private javax.swing.JButton btnFUNCARD;
    private javax.swing.JButton btnGaRan;
    private javax.swing.JButton btnGamota;
    private javax.swing.JButton btnGate;
    private javax.swing.JButton btnGosu;
    private javax.swing.JButton btnHaoHao;
    private javax.swing.JButton btnHatE;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnKulgame;
    private javax.swing.JButton btnMIGAME;
    private javax.swing.JButton btnMiTrung;
    private javax.swing.JButton btnMiY;
    private javax.swing.JButton btnNabati;
    private javax.swing.JButton btnNuiXaoBo;
    private javax.swing.JButton btnPepsi;
    private javax.swing.JButton btnPocari;
    private javax.swing.JButton btnSOHAME;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSinhToDau;
    private javax.swing.JButton btnSprite;
    private javax.swing.JButton btnString;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnVCOIN;
    private javax.swing.JButton btnVGP;
    private javax.swing.JButton btnZing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelChonMenhGia;
    private javax.swing.JPanel jPanelDoAnCon;
    private javax.swing.JPanel jPanelNapThe;
    private javax.swing.JPanel jPanelNhaCungCap;
    private javax.swing.JPanel jPanelNuocUon;
    private javax.swing.JPanel jPanelThoanhToan;
    private javax.swing.JPanel jPaneldDoAn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTabbedPane jtbChinh;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblGiamGia;
    private javax.swing.JLabel lblThanhToan;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JLabel txtGiamGIa;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txtThanhToan;
    private javax.swing.JLabel txtTongTien;
    // End of variables declaration//GEN-END:variables
}
